apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  labels:
    name: app-of-apps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/bfritscher/argocd-test.git
    targetRevision: HEAD
    path: .
    directory:
      include: 'application*.yaml'
      recurse: true
  syncPolicy:
    automated: {}
