apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hec-surveillance-frontend
  name: hec-surveillance-frontend
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: hec-surveillance-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hec-surveillance-frontend
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: hec-surveillance-frontend
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

