apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weblate
  namespace: argocd
  labels:
    name: weblate
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/WeblateOrg/helm.git
    path: charts/weblate
    targetRevision: weblate-0.5.3
    helm:
      valuesObject:
        adminEmail: admin@example.com
        adminPassword: admin
        # emailHost: smtp.example.com
        # emailUser:
        #emailPassword:
        # siteDomain:
        siteTitle: Test Weblate
        service:
          type: LoadBalancer
          port: 8083
        ingress:
          enabled: true
          hosts:
            - host:
              paths:
                - path: /
