apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: surveillance-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev
  source:
    repoURL: https://github.com/bfritscher/argocd-test.git
    path: nginx-dev
    targetRevision: HEAD
    directory:
      recurse: true