apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  labels:
    name: nginx  
spec:
  destination:
    name: nginx
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
  - repoURL: 'oci://registry-1.docker.io/bitnamicharts/nginx'
    targetRevision: 15.4.3
    helm:
      valueFiles:
      - $values/nginx/values.yaml
  - repoURL: 'https://github.com/bfritscher/argocd-test.git'
    targetRevision: main
    ref: values
